/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonFooter: typeof import('./../components/commonFooter.vue')['default']
    CommonHeader: typeof import('./../components/commonHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Hello: typeof import('./../components/Hello.vue')['default']
    IEpSuccessFilled: typeof import('~icons/ep/success-filled')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
